import { BadRequestException, ForbiddenException, Inject, Injectable, NotFoundException } from "@nestjs/common";
import type { RivalAnalyticsRequestResult, WorkplaceType } from "@iwtr/shared-types";
import { PrismaService } from "../../prisma/prisma.service";
import { FlagCalculatorService } from "../flags/flag-calculator.service";
import { getQuestionsFor } from "../reviews/survey-questions.data";
import { tallyQuestions } from "../reviews/survey-tally.util";
import { decideRivalAnalyticsAccess } from "./access-decision.util";
import { mostAgreedAndDisputed } from "./highlights.util";
import { summarizeCommentThemes, type ThemeMention } from "./comment-theme-summary.util";
import { buildRivalAnalyticsPdf } from "./pdf-report.builder";
import { EMAIL_PROVIDER, type IEmailProvider } from "./email/email-provider.interface";

@Injectable()
export class RivalAnalyticsService {
  constructor(
    private readonly prisma: PrismaService,
    private readonly flagCalculator: FlagCalculatorService,
    @Inject(EMAIL_PROVIDER) private readonly emailProvider: IEmailProvider,
  ) {}

  /**
   * requestingUserId/requestingCompanyId: the approved owner asking for
   * insight into a competitor. targetCompanySlug: the rival being analyzed
   * — its report goes to the REQUESTER's own contact info, never to the
   * rival itself.
   */
  async requestReport(requestingUserId: string, requestingCompanyId: string, targetCompanySlug: string): Promise<RivalAnalyticsRequestResult> {
    const ownership = await this.requireApprovedOwnership(requestingUserId, requestingCompanyId);

    const requestingCompany = await this.prisma.company.findUniqueOrThrow({ where: { id: requestingCompanyId } });
    const targetCompany = await this.prisma.company.findUnique({ where: { slug: targetCompanySlug } });
    if (!targetCompany) {
      throw new NotFoundException("Company not found");
    }
    if (targetCompany.id === requestingCompanyId) {
      throw new BadRequestException("Rival Analytics is for comparing against a different company, not your own.");
    }

    const access = decideRivalAnalyticsAccess({
      rivalAnalyticsTier: ownership.rivalAnalyticsTier,
      rivalAnalyticsFreeRequestUsed: ownership.rivalAnalyticsFreeRequestUsed,
    });

    if (!access.allowed) {
      const priceTry = process.env.RIVAL_ANALYTICS_PULL_PRICE_TRY;
      return {
        status: "PAYMENT_REQUIRED",
        priceNote: priceTry
          ? `This report costs ${priceTry} TRY. Payment is not wired up yet.`
          : "Pricing for this report has not been configured yet.",
      };
    }

    if (access.usedFreeCredit) {
      await this.prisma.companyOwner.update({
        where: { id: ownership.id },
        data: { rivalAnalyticsFreeRequestUsed: true },
      });
    }

    const pdfBuffer = await buildRivalAnalyticsPdf(await this.aggregateReportData(targetCompany.id, targetCompany.name, requestingCompany.name, ownership.rivalAnalyticsTier));

    const recipientEmail = requestingCompany.contactEmail ?? (await this.prisma.user.findUniqueOrThrow({ where: { id: requestingUserId } })).email;
    if (!recipientEmail) {
      throw new BadRequestException("No contact email on file to send this report to.");
    }

    await this.emailProvider.sendEmail(
      recipientEmail,
      `Rival Analytics: ${targetCompany.name}`,
      `Attached is your requested Rival Analytics report for ${targetCompany.name}, generated by iworkedthere.com.`,
      [{ filename: `rival-analytics-${targetCompany.slug}.pdf`, content: pdfBuffer, contentType: "application/pdf" }],
    );

    await this.prisma.auditLog.create({
      data: {
        actorUserId: requestingUserId,
        action: "RIVAL_ANALYTICS_REQUESTED",
        targetType: "Company",
        targetId: targetCompany.id,
        metadata: { requestingCompanyId, usedFreeCredit: access.usedFreeCredit },
      },
    });

    return { status: "SENT", recipientEmail, usedFreeCredit: access.usedFreeCredit };
  }

  private async aggregateReportData(
    targetCompanyId: string,
    targetCompanyName: string,
    requestingCompanyName: string,
    requesterTier: "STARTER" | "PRO" | "ENTERPRISE" | null,
  ) {
    const [targetCompany, aggregate, publishedReviews] = await Promise.all([
      this.prisma.company.findUniqueOrThrow({ where: { id: targetCompanyId } }),
      this.prisma.companyAggregateScore.findUnique({ where: { companyId: targetCompanyId } }),
      this.prisma.review.findMany({
        where: { companyId: targetCompanyId, status: "PUBLISHED" },
        select: { workplaceType: true, surveyAnswers: true, generalThoughts: true },
      }),
    ]);

    // Merged across every workplaceType the company has — this report is a
    // single at-a-glance summary, not a per-type breakdown like the public
    // company page.
    const allQuestionStats = (targetCompany.workplaceTypes as WorkplaceType[]).flatMap((workplaceType) => {
      const reviewsForType = publishedReviews.filter((r) => r.workplaceType === workplaceType);
      const questions = getQuestionsFor(workplaceType);
      return tallyQuestions(reviewsForType, questions);
    });

    const vibeFlags = (targetCompany.workplaceTypes as WorkplaceType[]).flatMap((workplaceType) => {
      const reviewsForType = publishedReviews.filter((r) => r.workplaceType === workplaceType);
      const questions = getQuestionsFor(workplaceType);
      return this.flagCalculator.computeVibeFlags({
        workplaceType,
        totalReviews: reviewsForType.length,
        questions: tallyQuestions(reviewsForType, questions),
      });
    });

    const commentThemes: ThemeMention[] = summarizeCommentThemes(
      publishedReviews.map((r) => r.generalThoughts).filter((t): t is string => !!t),
    );

    return {
      targetCompanyName,
      requestingCompanyName,
      requesterTier,
      generatedAt: new Date(),
      overallRating: aggregate && aggregate.reviewCount > 0 ? aggregate.overallAvg : null,
      reviewCount: aggregate?.reviewCount ?? 0,
      ...mostAgreedAndDisputed(allQuestionStats),
      vibeFlags,
      commentThemes,
    };
  }

  // Duplicated rather than cross-imported from OwnerService — matches this
  // codebase's existing module-per-feature convention.
  private async requireApprovedOwnership(userId: string, companyId: string) {
    const ownership = await this.prisma.companyOwner.findUnique({
      where: { userId_companyId: { userId, companyId } },
    });
    if (!ownership || ownership.claimStatus !== "APPROVED") {
      throw new ForbiddenException("You are not an approved owner of this company");
    }
    return ownership;
  }
}
